// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').directive('animatedArrow', function() {
  return {
    restrict: 'A',
    link: function(scope, element, attrs) {
      var go, num, parentLength;
      parentLength = $(element.parent()).width();
      num = 0;
      go = function() {
        $(element).css('left', (num++ % 2 * 42 + 5) + '%');
        return $(element).animate({
          left: '+=' + parentLength * 0.42
        }, 3000, go);
      };
      return go();
    }
  };
});
