// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').directive('feedback', [
  '$cookies', function($cookies) {
    return {
      templateUrl: 'includes/partials/feedback.html',
      restrict: 'E',
      link: function(scope, element, attrs) {
        var checkOverSubmitted;
        scope.firstTime = false;
        scope.submitted = false;
        checkOverSubmitted = function() {
          if (parseInt($cookies.iUltimateFeedbacked) > 15) {
            return scope.tooMuchSubmitted = true;
          }
        };
        checkOverSubmitted();
        setTimeout(function() {
          return scope.closeModal = function() {
            return scope.firstTime = false;
          };
        }, 1000);
        scope.closeModal = function() {
          scope.firstTime = false;
          try {
            return $('.first-time-modal').remove();
          } catch (_error) {}
        };
        setTimeout(function() {
          return scope.closeEmail = function() {
            return scope.emailOpen = false;
          };
        }, 1000);
        scope.closeEmail = function() {
          scope.emailOpen = false;
          try {
            return $('.email-modal').remove();
          } catch (_error) {}
        };
        scope.submitEmail = function(email, subject, message) {
          var submitted;
          if (scope.isValid(email, message)) {
            scope.closeEmail();
            $cookies.iUltimateFeedbacked = $cookies.iUltimateFeedbacked ? String(parseInt($cookies.iUltimateFeedbacked) + 1) : '1';
            return checkOverSubmitted();
          } else {
            return submitted = true;
          }
        };
        scope.isValid = function(email, message) {
          return /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(email) && (message !== void 0 ? message.length > 10 : true);
        };
        if (!$cookies.iUltimateVisited) {
          scope.firstTime = true;
        }
        return $cookies.iUltimateVisited = String(new Date().getTime());
      }
    };
  }
]);
