// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').directive('playerStatTable', function($routeParams, playerStats, filter) {
  return {
    templateUrl: 'includes/partials/playerStatTable.html',
    restrict: 'E',
    scope: {
      playerName: '='
    },
    link: function(scope, element, attrs) {
      var init;
      scope.included = filter.included;
      scope.$watch('included', function() {
        scope.myStats = typeof playerStats.getAll === "function" ? playerStats.getAll()[scope.playerName] : void 0;
        return scope.teamAverage = typeof playerStats.getAverages === "function" ? playerStats.getAverages() : void 0;
      });
      playerStats.then(function(response) {
        playerStats = response;
        return init();
      });
      return init = function() {
        scope.playerStats = playerStats.getAll()[scope.playerName].stats;
        scope.teamAverage = playerStats.getAverages();
        return scope.statTypes = _.keys(scope.playerStats).sort();
      };
    }
  };
});
