// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').factory('lineStats', function($q, team, allGames, filter) {
  var api, deferred, getStats, includedGames;
  getStats = function(players) {
    var consideredPoints, result;
    result = {};
    return consideredPoints = [];
  };
  api = {
    getPlayers: function() {
      return _(team.players).pluck('name');
    },
    getStats: getStats
  };
  deferred = $q.defer();
  includedGames = null;
  $q.all([team, allGames]).then(function(response) {
    includedGames = filter.included;
    team = response[0];
    deferred.resolve(api);
    _(includedGames).each(function(game) {
      return _(game.points).each(function(point) {
        if (_(point.line).intersection(players).length === players.length) {
          return consideredPoints.push(point);
        }
      });
    });
    result.consideredPoints = consideredPoints;
    return result;
  });
  return deferred.promise;
});
