// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').factory('lineStats', function($q, allGames, team) {
  var api, deferred;
  deferred = $q.defer();
  $q.all([allGames, team]).then(function(response) {
    allGames = response[0];
    team = response[1];
    return deferred.resolve(api);
  });
  api = {
    getPlayers: function() {
      return _(team.players).pluck('name');
    }
  };
  return deferred.promise;
});
