// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').factory('lineStats', function($q, allGames, team) {
  var api, deferred, getStats;
  deferred = $q.defer();
  $q.all([allGames, team]).then(function(response) {
    allGames = response[0];
    team = response[1];
    return deferred.resolve(api);
  });
  getStats = _.memoize(function(players) {
    var consideredPoints, result;
    result = {};
    consideredPoints = [];
    _(allGames).each(function(game) {
      return _(game.points).each(function(point) {
        if (_(point.line).intersection(players).length === players.length) {
          return consideredPoints.push(point);
        }
      });
    });
    result.consideredPoints = consideredPoints;
    return result;
  });
  api = {
    getPlayers: function() {
      return _(team.players).pluck('name');
    },
    getStats: getStats
  };
  return deferred.promise;
});
