// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').controller('GamesCtrl', function($scope, $q, allGames, teamStats, playerStats) {
  $scope.loading = true;
  return $q.all([allGames, teamStats, playerStats]).then(function() {
    return $scope.loading = false;
  });
});
