// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').controller('GamesCtrl', function($scope, $q, allGames, teamStats, playerStats, gameStats) {
  var games, gsApi, openPoints, psApi, scope;
  games = null;
  gsApi = null;
  psApi = null;
  scope = $scope;
  scope.loading = true;
  $q.all([allGames, playerStats, gameStats]).then(function(responses) {
    games = responses[0];
    psApi = responses[1];
    gsApi = responses[2];
    scope.select(_(games).max(function(game) {
      return game.msSinceEpoch;
    }));
    return scope.loading = false;
  });
  allGames.then(function(games) {
    scope.games = games;
    return scope.sortedGames = _(games).toArray();
  });
  scope.isSelectedGame = function(game) {
    return game === scope.selectedGame;
  };
  scope.select = function(game) {
    scope.gameLoading = true;
    scope.selectedGame = game;
    scope.gameStats = gsApi.getFor(game);
    return scope.gameLoading = false;
  };
  openPoints = {};
  scope.togglePoints = function(points, only) {
    if (only) {
      openPoints = {};
    }
    return _(_(points).pluck('$$hashKey')).each(function(id) {
      return openPoints[id] = !openPoints[id];
    });
  };
  return scope.isOpen = function(point) {
    return openPoints[point['$$hashKey']];
  };
});
