// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').controller('LineCtrl', function($scope, $q, playerStats, lineStats, Line) {
  var lsApi, scope;
  scope = $scope;
  scope.dragging;
  scope.selectedLine;
  scope.lines = {};
  $scope.loading = true;
  lsApi = null;
  lineStats.then(function(response) {
    lsApi = response;
    $scope.players = lsApi.getPlayers();
    return $scope.loading = false;
  });
  scope.setDragging = function(player) {
    return scope.dragging = player;
  };
  scope.addLine = function() {
    var line;
    line = new Line;
    scope.lines[line.id] = line;
    return scope.selectedLine = line;
  };
  scope.removeLine = function(line) {
    return delete scope.lines[line.id];
  };
  return scope.addLine();
});
