// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').controller('LineCtrl', function($scope, $q, playerStats, allGames) {
  var games, psApi, scope;
  scope = $scope;
  $scope.loading = true;
  games = null;
  psApi = null;
  return $q.all([playerStats, allGames]).then(function(response) {
    games = response[1];
    psApi = response[0];
    $scope.players = psApi.getFrom(games);
    return $scope.loading = false;
  });
});
