// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').controller('PlayerCtrl', function($scope, $routeParams, $q, playerStats, allGames) {
  var players, scope;
  scope = $scope;
  scope.loading = true;
  players = null;
  return $q.all([playerStats, allGames]).then(function(responses) {
    playerStats = responses[0];
    allGames = responses[1];
    players = playerStats.getFrom(allGames);
    scope.player = players[decodeURI($routeParams.playerNameUri)];
    return scope.loading = false;
  });
});
