// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('newBetaApp').controller('PlayerCtrl', function($scope, $routeParams, $q, playerStats, allGames, playerExtensionStats) {
  var playerName, players, scope;
  scope = $scope;
  scope.loading = true;
  players = null;
  playerName = decodeURI($routeParams.playerNameUri);
  return $q.all([playerStats, allGames, playerExtensionStats]).then(function(responses) {
    playerStats = responses[0];
    allGames = responses[1];
    playerExtensionStats = responses[2];
    players = playerStats.getFrom(allGames);
    scope.player = players[playerName];
    scope.loading = false;
    playerExtensionStats.setPlayer(playerName);
    playerExtensionStats.setGames(allGames);
    return scope.targetStats = playerExtensionStats.getTargetMap();
  });
});
